#!/bin/bash

wd=$(readlink -m $1)

if [ ! -d "$wd" ]; then
  echo "$1 is not a directory"
  exit
fi

find $wd -type d -name '.git' | \
  parallel --no-notice "echo -e '\e[34m{.}\e[0m'; git -c color.ui=always --git-dir={} --work-tree={.} ${@:2}; echo -e '\n'"
